### PR TITLE
initial look at indicating if user is not the owner

### PR DESCRIPTION
**Pull request by paul90**
this does not fully work as the server does not update `isOwner` in the client when the user authenticates.

### CODE REVIEW

**Comment by WardCunningham** [comment]
We're making some subtle but important distinctions here. I see no problem going ahead if we are slow to provide accurate information. (Refresh to be sure.)

I'm more concerned that we are able to tell how we are logged in and what we can expect having done so. I offer some suggestions in a page of analysis: http://ward.asia.wiki.org/am-i-logged-in-yet.html

> Lock icon should show unlocked only when authenticated and authorized. Authenticated but unauthorized should show tilted closed lock. Like neighbors, tilted means tried but didn't work. By analogy, lock could spin while authenticating.

> Site ownership should show as "not yet owned", "owned by you" or "owned by name-or-id".

> Hover over "owned by you" should show which account is the actual owner as one might have many

I'm getting multiple hovers over the lock. Hover text does not yet recognize login-to-view. 

The key icon makes sense to me. "Grab the Key to Claim." Can we make this the only icon when a site is unowned and login will result in claim?

This is going to require some attention to make intuitive and consistent across all our security modules. Please don't think I am complaining.

**Comment by WardCunningham** [comment]
I forgot to mention, I have installed this code merged with our other recent changes. This is certainly a step in the right direction.

**Comment by WardCunningham** [comment]
This and corresponding commit in wiki-client work together to meet cors expectations.
https://github.com/fedwiki/wiki-client/pull/220

**Comment by paul90** [comment]
Published as + wiki-security-passportjs@0.3.1

**Pull request merged**
